services:
  postgres:
    image: postgres:15
    container_name: cybersec_db
    environment:
      POSTGRES_USER: saas
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: saas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cybersec_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  clamav:
    image: clamav/clamav:latest
    container_name: cybersec_clamav
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
    healthcheck:
      test: ["CMD", "clamdscan", "--ping", "1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:
  clamav_data: